### ISSUE TITLE
Handle dots in directory names

### ISSUE THREAD

**Issue by paul-rogers** [linuxmint/bulky#12]
Great addition to Linux Mint!

I have a set of directories with names like `foo.bar-abc`, `foo.bar-def`. I want to remove the `foo.bar` part. However, Bulky seems to think the dot is an extension. If I try to "Rename", then "foo.bar-" won't match anything. If I try to "Remove", then Bulky removes *n* characters from both the "foo" part and the "bar-" part, leaving, when n=2, "o.r-def". If I choose name-only, then the removing stops at the dot so that, even if I ask to remove 8 characters, I'm left with ".bar-abc", etc.

What I expected was that, in Replace mode, if I type "foo.bar-" in the Find field, and nothing in the Replace field, that the prefix would be removed, even if it happens to include a dot. In addition to the three choices now ("Name only", "Extension only" and "Name and Extension"), should there also be an option for "Ignore Extension"? Or, auto-ignore extensions on directory names? (Though, we'd still want to do this for file names, see below.)

A workaround is to first replace the "foo" portion using "Name only" with blanks, leaving ".bar-abc" etc. Then, switch to "Extension Only" and replace ".bar-" with blank. This leaves me with ".abc", ".def", which is not quite what I wanted (I wanted to remove the dot, which is not an extension here.)

The key is that, in Linux, unlike Windows, the dot is not special; it is just a convention that is often followed to indicate an extension, but it is perfectly valid to use the dot elsewhere, especially in directory names. Imagine server logs with an IP address: `123.456.789.abc.log` or in domain names `foo.com.log`.

Thanks!

**Comment by Piiit** [comment]
@mtwebster 
Hi, I have the same issue. The Find contains "it.bz.beacon" in the first screenshot, and "it.bz.beacon." in the second. Replace is empty.

Please see the following screenshots:

This one is working, because I leave the last dot (same for Name only, Name + Extension dropdown selection):
![Selection_101](https://user-images.githubusercontent.com/6096063/128305305-1963ceae-783c-48d9-8999-a036b36fc4fc.png)

Here, I think the pattern matching assumes the last dot separates the extension, but folders do not have extensions:
![Selection_102](https://user-images.githubusercontent.com/6096063/128305415-3ea329a2-5630-4853-ae0f-411792e48d8c.png)

I suggest that for files, the dropdown "Name + Extension" should not tread the last dot as something special, and for folders this should be the default for all dropdown selection. I talk about the right dropdown...

I would consider this a bug, not an enhancement... because it is not correct for folders IMO. Other than that it is a very useful addition to nemo... thanks for that.

Cheers

**Comment by mtwebster** [comment]
Unzip this and copy to `/usr/lib/bulky`:

[bulky.zip](https://github.com/linuxmint/bulky/files/6939181/bulky.zip)

I think this is what you want, if you select name+extension
